2024-01-26 17:46:14,555 - ERROR - name 'optyka' is not defined
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 179, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 68, in events
    optyka.gui.polygonDrawing.addPoint(self.mousepos)
NameError: name 'optyka' is not defined
2024-01-26 17:47:08,043 - ERROR - module 'optyka' has no attribute 'gui'
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 180, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 69, in events
    optyka.gui.polygonDrawing.addPoint(self.mousepos)
AttributeError: module 'optyka' has no attribute 'gui'
2024-01-26 17:47:38,287 - ERROR - module 'optyka.gui' has no attribute 'polygonDrawing'
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 181, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 70, in events
    optyka.gui.polygonDrawing.addPoint(self.mousepos)
AttributeError: module 'optyka.gui' has no attribute 'polygonDrawing'
2024-01-26 17:48:00,478 - ERROR - list index out of range
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 182, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 84, in events
    optyka.gui.polygonDrawing.createPolygon()
  File "D:\Python\optyka\gui\polygonDrawing.py", line 24, in createPolygon
    gameobjects.GameObject.render(Adam)
  File "D:\Python\optyka\classes\gameobjects.py", line 66, in render
    self.get_slopes()
  File "D:\Python\optyka\classes\gameobjects.py", line 58, in get_slopes
    self.slopes.append((self.points[len(self.points)-1],self.points[0]))
IndexError: list index out of range
2024-01-26 17:49:32,520 - ERROR - module 'pygame' has no attribute 'K_ENTER'
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 182, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 83, in events
    elif event.key == pygame.K_ENTER:
AttributeError: module 'pygame' has no attribute 'K_ENTER'
2024-01-26 17:49:56,237 - ERROR - module 'pygame' has no attribute 'K_Enter'
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 182, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 83, in events
    elif event.key == pygame.K_Enter:
AttributeError: module 'pygame' has no attribute 'K_Enter'
2024-01-26 17:50:07,259 - ERROR - module 'pygame' has no attribute 'K_Enter'
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 182, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 83, in events
    elif event.key == pygame.K_Enter:
AttributeError: module 'pygame' has no attribute 'K_Enter'
2024-01-26 17:50:20,868 - ERROR - module 'pygame' has no attribute 'K_enter'
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 182, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 83, in events
    elif event.key == pygame.K_enter:
AttributeError: module 'pygame' has no attribute 'K_enter'
2024-01-26 17:50:50,098 - ERROR - module 'pygame' has no attribute 'K_enter'
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 183, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 84, in events
    elif event.key == pygame.K_enter:
AttributeError: module 'pygame' has no attribute 'K_enter'
2024-01-26 17:51:29,786 - ERROR - module 'pygame' has no attribute 'K_enter'
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 183, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 84, in events
    elif event.key == pygame.K_enter:
AttributeError: module 'pygame' has no attribute 'K_enter'
2024-01-26 18:00:51,211 - ERROR - GameObject.printSelf() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 177, in loop
    GameObject.printSelf()
TypeError: GameObject.printSelf() missing 1 required positional argument: 'self'
2024-01-26 18:08:02,472 - ERROR - non-integer arg 1 for randrange()
Traceback (most recent call last):
  File "D:\Python\lib\random.py", line 303, in randrange
    istart = _index(start)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 177, in loop
    self.render()
  File "D:\Python\optyka\classes\game.py", line 117, in render
    object.render()
  File "D:\Python\optyka\classes\bin.py", line 38, in render
    self.particle_system.update()
  File "D:\Python\optyka\classes\parkinson.py", line 33, in update
    particle.update()
  File "D:\Python\optyka\classes\parkinson.py", line 17, in update
    self.x += random.randint(0.5 * self.vx, 2 * self.vx)
  File "D:\Python\lib\random.py", line 370, in randint
    return self.randrange(a, b+1)
  File "D:\Python\lib\random.py", line 309, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()
2024-01-26 18:12:30,736 - ERROR - Library not initialized
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 183, in loop
    self.achievements.fps_achievements()
  File "D:\Python\optyka\classes\achievements.py", line 67, in fps_achievements
    if int(game.Game.return_fps(self.game)) < 10:
  File "D:\Python\optyka\classes\game.py", line 56, in return_fps
    return self.displayFPS()
  File "D:\Python\optyka\classes\game.py", line 165, in displayFPS
    fps_text = self.font.render(f"FPS: {int(fps)}", True, "white")
pygame.error: Library not initialized
2024-01-26 18:19:33,632 - ERROR - display Surface quit
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 30, in main
    startscreen = ss.StartScreen(width, height)
  File "D:\Python\optyka\gui\startscreen.py", line 37, in __init__
    self.mainloop()
  File "D:\Python\optyka\gui\startscreen.py", line 52, in mainloop
    self.render()
  File "D:\Python\optyka\gui\startscreen.py", line 68, in render
    self.screen.fill('black')
pygame.error: display Surface quit
2024-01-26 18:23:31,790 - ERROR - name 'Adam' is not defined
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 177, in loop
    self.render()
  File "D:\Python\optyka\classes\game.py", line 116, in render
    Adam.render()
NameError: name 'Adam' is not defined
2024-01-26 18:25:11,895 - ERROR - local variable 'object' referenced before assignment
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 178, in loop
    self.render()
  File "D:\Python\optyka\classes\game.py", line 106, in render
    print(object)
UnboundLocalError: local variable 'object' referenced before assignment
2024-01-26 18:31:10,090 - ERROR - module 'classes.game' has no attribute 'sorted_objects'
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 184, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 84, in events
    optyka.gui.polygonDrawing.createPolygon()
  File "D:\Python\optyka\gui\polygonDrawing.py", line 24, in createPolygon
    print(game.sorted_objects)
AttributeError: module 'classes.game' has no attribute 'sorted_objects'
2024-01-26 18:32:43,634 - ERROR - module 'classes.game' has no attribute 'sorted_objects'
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 184, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 84, in events
    optyka.gui.polygonDrawing.createPolygon()
  File "D:\Python\optyka\gui\polygonDrawing.py", line 24, in createPolygon
    print(game.sorted_objects)
AttributeError: module 'classes.game' has no attribute 'sorted_objects'
2024-01-26 18:34:16,199 - ERROR - name 'sorted_objects' is not defined
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 184, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 86, in events
    print(sorted_objects)
NameError: name 'sorted_objects' is not defined
2024-01-26 18:36:15,083 - ERROR - name 'objects' is not defined
Traceback (most recent call last):
  File "D:\Python\optyka\main.py", line 38, in main
    game_instance.loop()
  File "D:\Python\optyka\classes\game.py", line 184, in loop
    self.events()
  File "D:\Python\optyka\classes\game.py", line 86, in events
    print(objects)
NameError: name 'objects' is not defined
